"""A very small Markdown renderer, for displaying stored digests.

The digests are machine-generated by ``telescope.render.markdown``, which uses a
deliberately narrow subset: headings, ``---``, bullets, blockquotes, paragraphs,
and inline bold/italic/code/links, with markdown metacharacters backslash-escaped
in the text. That is the whole grammar this renderer needs to support.

Writing it here instead of adding a Markdown dependency is the same trade the
rest of the project makes: the input is generated by our own code, so the
grammar is known, closed, and testable. Everything is HTML-escaped before any
tag is emitted, and only ``http(s)`` links are turned into anchors.
"""

from __future__ import annotations

import html
import re

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
# The label may itself contain brackets. Telescope escapes those in the source
# text (``[[Industry news] Headline](url)`` arrives as
# ``[\[Industry news\] Headline](url)``), so the label pattern allows one level
# of escaped nesting. Without it the outer link is not recognised at all and the
# URL leaks into the page as plain text.
LINK_RE = re.compile(r"\[((?:[^\[\]]|\[[^\[\]]*\])*)\]\(([^)\s]+)\)")

# The characters telescope's own renderer escapes with a backslash.
ESCAPABLE = frozenset("\\`*_[]<>|")

SAFE_SCHEMES = ("http://", "https://", "mailto:")


def _safe_url(url: str) -> str | None:
    """Return the URL when it is safe to put in an href, else None."""
    cleaned = url.strip()
    if not cleaned:
        return None
    lowered = cleaned.lower()
    if lowered.startswith(SAFE_SCHEMES):
        return cleaned
    # Bare relative links are fine; anything else (javascript:, data:) is not.
    if "/" in cleaned and ":" not in cleaned.split("/", 1)[0]:
        return cleaned
    return None


def inline(text: str) -> str:
    """Render inline markup, escaping everything that is not a tag we emit."""
    out: list[str] = []
    index = 0
    length = len(text)

    while index < length:
        char = text[index]

        if char == "\\" and index + 1 < length and text[index + 1] in ESCAPABLE:
            out.append(html.escape(text[index + 1]))
            index += 2
            continue

        if char == "`":
            close = text.find("`", index + 1)
            if close != -1:
                out.append(f"<code>{html.escape(text[index + 1 : close])}</code>")
                index = close + 1
                continue

        if text.startswith("**", index):
            close = text.find("**", index + 2)
            if close != -1:
                out.append(f"<strong>{inline(text[index + 2 : close])}</strong>")
                index = close + 2
                continue

        if char == "*":
            close = text.find("*", index + 1)
            if close != -1:
                out.append(f"<em>{inline(text[index + 1 : close])}</em>")
                index = close + 1
                continue

        if char == "[":
            match = LINK_RE.match(text, index)
            if match:
                label, url = match.group(1), match.group(2)
                safe = _safe_url(url)
                if safe is None:
                    out.append(inline(label))
                else:
                    href = html.escape(safe, quote=True)
                    out.append(
                        f'<a href="{href}" target="_blank" '
                        f'rel="noopener noreferrer">{inline(label)}</a>'
                    )
                index = match.end()
                continue

        out.append(html.escape(char))
        index += 1

    return "".join(out)


def _starts_block(line: str) -> bool:
    stripped = line.strip()
    return (
        not stripped
        or stripped == "---"
        or stripped.startswith(">")
        or stripped.startswith("- ")
        or bool(HEADING_RE.match(stripped))
    )


def render(markdown: str) -> str:
    """Turn digest Markdown into HTML."""
    lines = (markdown or "").replace("\r\n", "\n").split("\n")
    blocks: list[str] = []
    seen: dict[str, int] = {}
    index = 0

    while index < len(lines):
        stripped = lines[index].strip()

        if not stripped:
            index += 1
            continue

        if stripped == "---":
            blocks.append("<hr>")
            index += 1
            continue

        heading = HEADING_RE.match(stripped)
        if heading:
            level = len(heading.group(1))
            title = heading.group(2).strip()
            anchor = ""
            if level == 2:
                # Section headings get a stable id so the digest page can link
                # straight to "Layoffs & closures".
                plain = re.sub(r"\\(.)", r"\1", title)
                seen[plain] = seen.get(plain, 0) + 1
                anchor = f' id="{slugify(plain, seen[plain])}"'
            blocks.append(f"<h{level}{anchor}>{inline(title)}</h{level}>")
            index += 1
            continue

        if stripped.startswith(">"):
            quoted: list[str] = []
            while index < len(lines) and lines[index].strip().startswith(">"):
                quoted.append(lines[index].strip().lstrip(">").strip())
                index += 1
            body = "".join(f"<p>{inline(line)}</p>" for line in quoted if line)
            blocks.append(f"<blockquote>{body}</blockquote>")
            continue

        if stripped.startswith("- "):
            items: list[str] = []
            while index < len(lines) and lines[index].strip().startswith("- "):
                items.append(lines[index].strip()[2:].strip())
                index += 1
            body = "".join(f"<li>{inline(item)}</li>" for item in items)
            blocks.append(f"<ul>{body}</ul>")
            continue

        # Paragraph. A trailing double space is Markdown's hard line break, and
        # the digest header relies on it.
        paragraphs: list[str] = []
        while index < len(lines) and not _starts_block(lines[index]):
            # Check for the trailing double space *before* stripping it: that
            # is Markdown's hard line break, and the digest header uses it.
            hard_break = lines[index].endswith("  ")
            paragraphs.append(
                inline(lines[index].strip()) + ("<br>" if hard_break else "")
            )
            index += 1
        blocks.append("<p>" + "".join(paragraphs) + "</p>")

    return "\n".join(blocks)


def sections(markdown: str) -> list[tuple[str, int]]:
    """``[(heading, occurrence_index), ...]`` for building a table of contents."""
    found: list[tuple[str, int]] = []
    seen: dict[str, int] = {}
    fence = False
    for line in (markdown or "").split("\n"):
        if line.strip().startswith("```"):
            fence = not fence
            continue
        if fence:
            continue
        match = HEADING_RE.match(line.strip())
        if match and len(match.group(1)) == 2:
            title = re.sub(r"\\(.)", r"\1", match.group(2).strip())
            seen[title] = seen.get(title, 0) + 1
            found.append((title, seen[title]))
    return found


def slugify(title: str, occurrence: int = 1) -> str:
    base = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "section"
    return base if occurrence == 1 else f"{base}-{occurrence}"
